### PR TITLE
Fix task no duplicate check and update UG

### LINKED ISSUE #179: [PE-D][Tester A] Feeding reminders persisting after deleting fish
Issue:
1. There is a `Tank feeding reminder` for a tank with 1 fish
2. That fish is deleted.
3. `Tank feeding reminder` for that fish remains.
4. Even after restarting the app, the reminder remains, and sometimes it gets shifted to the very bottom, below other manually added tasks.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Bransonlj/ped#3

### PR DESCRIPTION
**Pull request by bokuanT**
I intended to disallow duplicate tasks within the same tank. I have fixed the bug where dupes of tasks with no tanks can be made and tasks of same name but different tanks cannot be added. Update DG also

Close #179

### CODE REVIEW

File: src/main/java/seedu/address/model/task/Task.java [hunk 1]
```diff
@@ -78,7 +78,8 @@ public boolean equals(Object other) {
 
         Task otherTask = (Task) other;
         boolean bothHasTank = isTankRelatedTask() && otherTask.isTankRelatedTask();
-        boolean hasSameTank = bothHasTank && (tank.equals(otherTask.getTank()));
+        boolean bothNoTank = !isTankRelatedTask() && !otherTask.isTankRelatedTask();
+        boolean hasSameTank = (bothHasTank && (tank.equals(otherTask.getTank()))) || bothNoTank;
```
Comment (ryanchua00) [inline src/main/java/seedu/address/model/task/Task.java:82]: Includes tasks with no tanks in duplication detection by detecting a task with no tank as being in the same tank as other tasks with no tank

**Review by ryanchua00 — APPROVED** [review]
Good fix to functionality bug - duplicate tasks were not allowed, however bug in tasks with no tank would lead to no checks being done for them.
